"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
const digits=(v:string)=>v.replace(/[^0-9]/g,"");
const fmt=(v:any)=>Number(v||0).toLocaleString("ko-KR");
export default function DonationBoxAdmin(){
 const [data,setData]=useState<any>(null),[name,setName]=useState(""),[amount,setAmount]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[edit,setEdit]=useState<any>(null);
 const url=useMemo(()=>typeof window==="undefined"?"/overlay/donation-box":`${window.location.origin}/overlay/donation-box`,[]);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/donation-box?t=${Date.now()}`,{cache:"no-store"});setData(await r.json())}catch{}},[]); useEffect(()=>{void load()},[load]);
 const post=async(body:any)=>{setBusy(true);setMsg("");try{const r=await fetch("/api/admin/donation-box",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"오류");await load();return true}catch(e:any){setMsg(e.message||"오류가 발생했습니다.");return false}finally{setBusy(false)}};
 if(!data)return <main className="p-6 text-white">불러오는 중...</main>; const s=data.settings;
 const slider=(key:string,label:string,min:number,max:number)=><label className="block"><div className="mb-1 flex justify-between text-sm font-bold"><span>{label}</span><span>{s[key]}px</span></div><input className="w-full" type="range" min={min} max={max} value={s[key]} onChange={e=>setData({...data,settings:{...s,[key]:Number(e.target.value)}})}/></label>;
 return <main className="min-h-screen bg-[#090613] px-3 py-5 text-white md:px-6"><div className="mx-auto max-w-[1200px] space-y-5">
  <header><p className="text-sm font-black text-red-400">시청자 기부함</p><h1 className="text-3xl font-black">지폐 기부함 오버레이</h1><p className="mt-2 text-sm text-white/55">후원자와 금액을 수기로 추가하면 설정한 총금액을 기준으로 지폐 더미가 11단계로 쌓입니다. 방송 화면에는 지폐 더미와 현재 총 후원금만 표시됩니다.</p></header>
  {msg&&<div className="rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-red-200">{msg}</div>}
  <section className="rounded-2xl border border-white/10 bg-[#151027] p-4"><b>OBS / PRISM 주소</b><div className="mt-2 flex gap-2"><input readOnly value={url} className="min-w-0 flex-1 rounded-xl bg-[#090613] p-3 text-sm"/><button onClick={()=>navigator.clipboard.writeText(url)} className="rounded-xl bg-violet-600 px-5 font-black">복사</button></div></section>
  <section className="rounded-2xl border border-red-400/20 bg-[#151027] p-4"><div className="mb-3 flex items-end justify-between"><div><div className="text-sm text-white/50">현재 시청자 기부금</div><div className="text-3xl font-black text-red-400">{fmt(data.total)}원</div></div></div><div className="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="후원자 닉네임" className="rounded-xl bg-[#090613] p-3 font-bold"/><input inputMode="numeric" value={amount?fmt(amount):""} onChange={e=>setAmount(digits(e.target.value))} placeholder="후원 금액" className="rounded-xl bg-[#090613] p-3 font-bold"/><button disabled={busy} onClick={async()=>{if(await post({action:"add",donorName:name,amount:Number(amount)})){setName("");setAmount("")}}} className="rounded-xl bg-red-600 px-6 py-3 font-black">+ 후원 추가</button></div></section>
  <section className="rounded-2xl border border-white/10 bg-[#151027] p-4"><h2 className="mb-4 text-lg font-black">오버레이 디자인 설정</h2><div className="grid gap-4 md:grid-cols-2"><label><span className="text-sm font-bold">제목</span><input value={s.title} onChange={e=>setData({...data,settings:{...s,title:e.target.value}})} className="mt-1 w-full rounded-xl bg-[#090613] p-3"/></label><label><span className="text-sm font-bold">금액 위 문구</span><input value={s.bottomLabel} onChange={e=>setData({...data,settings:{...s,bottomLabel:e.target.value}})} className="mt-1 w-full rounded-xl bg-[#090613] p-3"/></label><label><span className="text-sm font-bold">목표 총금액 (100%)</span><input inputMode="numeric" value={fmt(s.targetAmount)} onChange={e=>setData({...data,settings:{...s,targetAmount:Number(digits(e.target.value))}})} className="mt-1 w-full rounded-xl bg-[#090613] p-3"/><span className="mt-1 block text-xs text-white/45">방송 화면에는 목표금액이나 퍼센트가 표시되지 않습니다.</span></label><label><span className="text-sm font-bold">지폐 크기 {s.noteScale}%</span><input type="range" min="60" max="150" value={s.noteScale} onChange={e=>setData({...data,settings:{...s,noteScale:Number(e.target.value)}})} className="mt-3 w-full"/></label>{slider("titleFontSize","제목 글씨",14,70)}{slider("amountFontSize","총액 글씨",16,80)}{slider("labelFontSize","안내문구 글씨",10,45)}{slider("donorFontSize","최근 후원자 글씨",10,40)}{slider("noteFontSize","지폐 안 글씨",7,22)}{slider("boxWidth","기부함 가로",260,700)}{slider("boxHeight","기부함 세로",240,700)}</div><button disabled={busy} onClick={()=>post({action:"settings",...s})} className="mt-5 w-full rounded-xl bg-red-600 py-3 font-black">디자인 설정 적용</button></section>
  <section className="rounded-2xl border border-white/10 bg-[#151027] p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">후원 입력 내역</h2><button onClick={()=>{if(confirm("후원 내역을 전부 초기화할까요?"))void post({action:"reset"})}} className="rounded-lg border border-red-400/30 px-3 py-2 text-sm font-black text-red-300">전체 초기화</button></div><div className="space-y-2">{data.entries.map((x:any)=><div key={x.id} className="flex flex-wrap items-center gap-2 rounded-xl bg-[#090613] p-3"><div className="min-w-[130px] flex-1 font-black">{x.donorName}</div><div className="font-black text-red-300">{fmt(x.amount)}원</div><button onClick={()=>setEdit({id:x.id,donorName:x.donorName,amount:String(x.amount)})} className="rounded-lg bg-white/10 px-3 py-2 text-sm font-bold">수정</button><button onClick={()=>post({action:"delete",id:x.id})} className="rounded-lg bg-red-500/15 px-3 py-2 text-sm font-bold text-red-300">삭제</button></div>)}</div></section>
  {edit&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl bg-[#151027] p-5"><h3 className="mb-3 text-xl font-black">후원 수정</h3><input value={edit.donorName} onChange={e=>setEdit({...edit,donorName:e.target.value})} className="mb-2 w-full rounded-xl bg-[#090613] p-3"/><input value={edit.amount?fmt(edit.amount):""} onChange={e=>setEdit({...edit,amount:digits(e.target.value)})} className="mb-4 w-full rounded-xl bg-[#090613] p-3"/><div className="flex gap-2"><button onClick={async()=>{if(await post({action:"edit",...edit,amount:Number(edit.amount)}))setEdit(null)}} className="flex-1 rounded-xl bg-red-600 py-3 font-black">저장</button><button onClick={()=>setEdit(null)} className="flex-1 rounded-xl bg-white/10 py-3 font-black">취소</button></div></div></div>}
 </div></main>
}
