const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),ts=require("typescript"),Module=require("node:module");
const file=path.join(__dirname,"../lib/minigame/engine.ts"),m=new Module(file,module);m.filename=file;m.paths=module.paths;m._compile(ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,file);const e=m.exports;
function walk(seed,fps=60){const s=e.makeWalker(seed);let frame=0;while(!s.fallen&&s.tick<e.HZ*e.WALK_SECONDS){const target=Math.min(e.HZ*e.WALK_SECONDS,Math.floor(++frame*e.HZ/fps));while(s.tick<target&&!s.fallen)e.stepWalker(s,0,seed);}return{version:1,end:s.tick,moves:[],reason:"complete"};}
function rect(b){for(let t=0;t<e.ROWS;t++)for(let l=0;l<e.COLS;l++)for(let r=l;r<e.COLS;r++)for(let bt=t;bt<e.ROWS;bt++){const s=e.selection(b,l,t,r,bt);if(s.sum===10)return[l,t,r,bt];if(s.sum>10)break;}return null;}
test("seeded boards are stable, bounded and initially solvable",()=>{for(let i=0;i<1000;i++){const b=e.makeBoard(i);assert.deepEqual(b,e.makeBoard(i));assert.equal(b.length,170);assert.ok(b.every(x=>x>=1&&x<=9));assert.equal(b[0]+b[1],10);}});
test("apple replay is replayed and score is calculated on the server",()=>{for(let seed=0;seed<35;seed++){const b=e.makeBoard(seed),moves=[];let score=0;for(let i=0;i<85;i++){const x=rect(b);if(!x)break;score+=e.removeSelection(b,...x);moves.push([i*800,...x]);}const r={version:1,end:120000,moves,reason:"complete"};assert.equal(e.verifyReplay("ten",seed,r).metric,score);assert.ok(score<=170);assert.throws(()=>e.verifyReplay("ten",seed,{...r,moves:[moves[0],moves[0]]}));assert.throws(()=>e.verifyReplay("ten",seed,{...r,moves:[[120000,0,0,1,0]]}));}});
test("30, 60, and 144 Hz simulations give identical survival records",()=>{for(let seed=0;seed<150;seed++){const a=walk(seed,30),b=walk(seed,60),c=walk(seed,144);assert.deepEqual(a,b);assert.deepEqual(b,c);assert.equal(e.verifyReplay("walk",seed,a).metric,Math.floor(a.end*100/120));assert.throws(()=>e.verifyReplay("walk",seed,{...a,end:a.end+1}));}});
test("survival rankings are independently recalculated from a 600 second replay",()=>{const seed=2026,s=e.makeWalker(seed),moves=[];let input=0;while(s.tick<72000){if(s.tick%12===0){const q=-(Math.sign(s.angle*5+s.velocity*2));if(q!==input){input=q;moves.push([s.tick,input]);}}e.stepWalker(s,input,seed);}assert.equal(e.verifyReplay("walk",seed,{version:1,end:72000,moves,reason:"complete",score:99999999}).metric,60000);assert.throws(()=>e.verifyReplay("walk",seed,{version:1,end:72001,moves,reason:"complete"}));});
test("malformed payloads and wrong rule versions fail closed",()=>{for(const r of [null,[],{}, {version:2,end:120000,moves:[],reason:"complete"},{version:1,end:NaN,moves:[],reason:"quit"}])assert.throws(()=>e.verifyReplay("ten",1,r));});
