import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import type { PoolConnection, RowDataPacket } from "mysql2/promise";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import db from "@/lib/db";
import type { Game } from "./engine";
export class ApiError extends Error { constructor(message:string,public status=400){super(message);} }
export type User={id:number;role:string;nickname:string};
export type SessionRow=RowDataPacket&{id:string;user_id:number;game:Game;rule_version:number;seed:number;status:string;metric:number;elapsed_ms:number;started_at:number;ended_at:number|null;expires_at:number;eligible:number};
export async function currentUser(admin=false):Promise<User>{const s=await getServerSession(authOptions);if(!s?.user?.email)throw new ApiError("로그인이 필요합니다.",401);const[rows]=await db.query<RowDataPacket[]>("SELECT id,role,nickname FROM users WHERE email=? LIMIT 1",[s.user.email]);if(!rows.length)throw new ApiError("닉네임 등록을 먼저 완료해 주세요.",403);if(admin&&rows[0].role!=="admin")throw new ApiError("관리자만 이용할 수 있습니다.",403);return rows[0] as User;}
export function guardOrigin(req:Request){const o=req.headers.get("origin"),site=req.headers.get("sec-fetch-site");if(site==="cross-site"||!o||new URL(o).origin!==new URL(req.url).origin)throw new ApiError("허용되지 않은 요청입니다.",403);}
export async function body(req:Request,max=210000){if(!req.headers.get("content-type")?.includes("application/json"))throw new ApiError("JSON 요청이 필요합니다.",415);if(Number(req.headers.get("content-length")||0)>max)throw new ApiError("기록 용량이 너무 큽니다.",413);if(!req.body)throw new ApiError("빈 요청입니다.");const rd=req.body.getReader(),chunks:Uint8Array[]=[];let n=0;while(true){const{done,value}=await rd.read();if(done)break;n+=value.byteLength;if(n>max){await rd.cancel();throw new ApiError("기록 용량이 너무 큽니다.",413);}chunks.push(value);}try{const d=JSON.parse(Buffer.concat(chunks).toString("utf8"));if(!d||typeof d!=="object"||Array.isArray(d))throw Error();return d;}catch{throw new ApiError("요청 형식이 올바르지 않습니다.");}}
export const uuid=(x:unknown):x is string=>typeof x==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
export const json=(d:unknown,s=200)=>NextResponse.json(d,{status:s,headers:{"Cache-Control":"no-store"}});
export function failure(e:unknown){if(e instanceof ApiError)return json({success:false,message:e.message},e.status);if((e as{code?:string})?.code==="ER_NO_SUCH_TABLE")return json({success:false,message:"미니게임 DB 설치가 필요합니다. 관리자에게 알려주세요."},503);console.error("[minigame]",(e as{code?:string})?.code||(e instanceof Error?e.name:"unknown"));return json({success:false,message:"기록 서버에 연결하지 못했습니다. 잠시 후 다시 시도해 주세요."},503);}
export async function transaction<T>(f:(c:PoolConnection)=>Promise<T>){const c=await db.getConnection();try{await c.beginTransaction();const x=await f(c);await c.commit();return x;}catch(e){await c.rollback();throw e;}finally{c.release();}}
export async function lockUser(c:PoolConnection,id:number){await c.query("SELECT id FROM users WHERE id=? FOR UPDATE",[id]);}
export async function rebuildBest(c:PoolConnection,user:number,game:Game){const[rows]=await c.query<RowDataPacket[]>("SELECT id,metric,ended_at FROM minigame_sessions WHERE user_id=? AND game=? AND status='finished' AND eligible=1 ORDER BY metric DESC,ended_at ASC,id ASC LIMIT 1",[user,game]);if(!rows.length){await c.query("DELETE FROM minigame_best WHERE user_id=? AND game=?",[user,game]);return;}const r=rows[0];await c.query("INSERT INTO minigame_best(game,user_id,session_id,metric,achieved_at)VALUES(?,?,?,?,?)ON DUPLICATE KEY UPDATE session_id=VALUES(session_id),metric=VALUES(metric),achieved_at=VALUES(achieved_at)",[game,user,r.id,r.metric,r.ended_at]);}
export function savedResult(s:SessionRow){return{success:true,id:s.id,status:s.status,metric:Number(s.metric),elapsedMs:Number(s.elapsed_ms),eligible:!!s.eligible,endedAt:s.ended_at?Number(s.ended_at):null};}
