import { broadcastOverlayChange } from "@/lib/overlay-realtime-server";
import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import db from "@/lib/db";
export const dynamic="force-dynamic";
async function admin(){const s=await getServerSession(authOptions);if(!s?.user?.email)return false;const [r]:any=await db.query("SELECT role FROM users WHERE email=? LIMIT 1",[s.user.email]);return r[0]?.role==="admin";}
export async function POST(req:Request){if(!(await admin()))return NextResponse.json({success:false},{status:403});const b=await req.json();await db.query(`CREATE TABLE IF NOT EXISTS dotori_walk_state (id INT NOT NULL PRIMARY KEY, plus_dotori BIGINT NOT NULL DEFAULT 0, minus_dotori BIGINT NOT NULL DEFAULT 0, total_used BIGINT NOT NULL DEFAULT 0, font_color VARCHAR(20) NOT NULL DEFAULT '#FFFFFF', plus_color VARCHAR(20) NOT NULL DEFAULT '#67E8F9', minus_color VARCHAR(20) NOT NULL DEFAULT '#FB7185', outline_color VARCHAR(20) NOT NULL DEFAULT '#000000', outline_width INT NOT NULL DEFAULT 4, distance_size INT NOT NULL DEFAULT 72, total_size INT NOT NULL DEFAULT 30, sub_size INT NOT NULL DEFAULT 26, plus_song_url TEXT, minus_song_url TEXT, updated_at DATETIME NULL)`);await db.query(`INSERT IGNORE INTO dotori_walk_state(id,updated_at) VALUES(1,NOW())`);
if(b.action==="saveSettings"){await db.query(`UPDATE dotori_walk_state SET font_color=?,plus_color=?,minus_color=?,outline_color=?,outline_width=?,distance_size=?,total_size=?,sub_size=?,plus_song_url=?,minus_song_url=?,updated_at=NOW() WHERE id=1`,[b.font_color||"#FFFFFF",b.plus_color||"#67E8F9",b.minus_color||"#FB7185",b.outline_color||"#000000",Math.max(0,Math.min(12,Number(b.outline_width)||0)),Math.max(30,Math.min(140,Number(b.distance_size)||72)),Math.max(16,Math.min(70,Number(b.total_size)||30)),Math.max(14,Math.min(60,Number(b.sub_size)||26)),String(b.plus_song_url||""),String(b.minus_song_url||"")]);await broadcastOverlayChange("dotori-walk-admin");return NextResponse.json({success:true});}
if(b.action==="reset"){await db.query(`UPDATE dotori_walk_state SET plus_dotori=0,minus_dotori=0,total_used=0,updated_at=NOW() WHERE id=1`);await broadcastOverlayChange("dotori-walk-admin");return NextResponse.json({success:true});}
return NextResponse.json({success:false,message:"잘못된 요청"},{status:400});}
