"use client";import{useCallback,useEffect,useRef,useState}from"react";import{signIn,useSession}from"next-auth/react";import GameCanvas,{type PlaySession}from"./GameCanvas";import{formatMetric,VERSION,type Game,type Replay}from"@/lib/minigame/engine";
type Rank={rank:number;nickname:string;metric:number};type Pending={id:string;game:Game;replay:Replay};const info={ten:{name:"도토리게임",hint:"도토리를 이어 점수를 올려요.",desc:"사과게임 방식으로 숫자 도토리를 드래그해 합계 10을 만들어요. 120초 동안 모은 점수로 경쟁해요."},walk:{name:"왕츄 오래걷기",hint:"흔들려도, 한 걸음 더.",desc:"왼쪽·오른쪽으로 균형을 잡아요. 생존 시간을 0.01초 단위로 기록해요."}};
async function req(url:string,init?:RequestInit){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),18000);try{const r=await fetch(url,{...init,signal:ctl.signal}),d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"요청을 처리하지 못했습니다.");return d;}catch(e){if(e instanceof Error&&e.name==="AbortError")throw Error("응답이 늦어요. 다시 시도해 주세요.");throw e;}finally{clearTimeout(t);}}
export default function Arcade(){const{data:auth,status:authStatus}=useSession(),[game,G]=useState<Game>("ten"),[session,S]=useState<PlaySession|null>(null),[phase,P]=useState("idle"),[stop,T]=useState(0),[error,E]=useState(""),[result,O]=useState<any>(null),[pending,Q]=useState<Pending|null>(null),[ranks,R]=useState<Rank[]>([]),[mine,M]=useState<any>(null),[rankError,RE]=useState(""),[rankLoading,RL]=useState(false),sid=useRef<string|null>(null),busy=useRef(false),seq=useRef(0),storageKey=auth?.user?.email?"wangchu-mini-pending-v1:"+auth.user.email:null,keyRef=useRef<string|null>(null);keyRef.current=storageKey;
const locked=["starting","playing","saving"].includes(phase)||!!pending;
const load=useCallback(async()=>{const n=++seq.current;RL(true);RE("");try{const d=await req("/api/game/mini/ranking?game="+game);if(seq.current===n){R(d.top);M(d.mine);}}catch(e){if(seq.current===n)RE(e instanceof Error?e.message:"랭킹 조회 실패");}finally{if(seq.current===n)RL(false);}},[game]);useEffect(()=>{R([]);M(null);void load();return()=>{seq.current++;};},[load]);
useEffect(()=>{if(!storageKey)return;try{const x=localStorage.getItem(storageKey);if(!x)return;const p=JSON.parse(x) as Pending;if(p.id&&["ten","walk"].includes(p.game)&&p.replay){Q(p);G(p.game);P("retry");E("저장 확인을 받지 못한 기록이 있어요. 기록 저장을 다시 눌러 주세요.");}}catch{E("보관된 기록을 읽지 못했습니다.");}},[storageKey]);useEffect(()=>{if(!locked)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f);},[locked]);
async function save(x:Pending){if(busy.current)return;busy.current=true;P("saving");E("");try{const d=await req("/api/game/mini/finish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:x.id,replay:x.replay})});O(d);Q(null);if(keyRef.current)try{localStorage.removeItem(keyRef.current);}catch{}P("done");void load();}catch(e){P("retry");E((e instanceof Error?e.message:"저장 실패")+" 기록은 이 브라우저에 보관했어요. 다시 전송할 수 있습니다.");}finally{busy.current=false;}}
function finished(replay:Replay){if(!session)return;const x={id:session.id,game,replay};Q(x);try{if(storageKey)localStorage.setItem(storageKey,JSON.stringify(x));}catch{E("임시 기록 저장에 실패했어요. 서버 저장이 끝날 때까지 이 화면을 유지해 주세요.");}void save(x);}
async function start(){if(locked||busy.current)return;if(authStatus!=="authenticated"){void signIn("google",{callbackUrl:"/game/mini"});return;}busy.current=true;P("starting");E("");O(null);S(null);try{if(!sid.current)sid.current=crypto.randomUUID();const d=await req("/api/game/mini/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:sid.current,game,mode:"free"})});if(d.version!==VERSION)throw Error("게임 규칙이 변경됐어요. 페이지를 새로고침해 주세요.");S({id:d.id,seed:d.seed,game:d.game,version:d.version});sid.current=null;P("playing");}catch(e){E(e instanceof Error?e.message:"시작 실패");P("idle");}finally{busy.current=false;}}
function change(g:Game){if(locked)return;G(g);S(null);O(null);E("");P("idle");T(0);sid.current=null;}
const g=info[game];return <main className="mg-shell"><div className="mg-wrap"><header className="mg-header"><a href="/" className="mg-brand">W <span>왕츄 오락실<small>WANGCHU ARCADE</small></span></a><a href="/game" className="mg-back">기존 게임 ↗</a></header><section className="mg-intro"><div><p className="mg-eyebrow">작은 도전, 새로운 최고기록</p><h1>오늘의 한 판<span>.</span></h1><p>가볍게 시작해서, 최고기록까지.</p></div><span className="mg-free">● 무료 플레이</span></section>
<nav className="mg-tabs">{(["ten","walk"] as Game[]).map(x=><button key={x} disabled={locked} className={game===x?"is-active":""} onClick={()=>change(x)}><span>{x==="ten"?"🌰":"👑"}</span><span><small>{x==="ten"?"사과게임 방식":"균형 챌린지"}</small><b>{info[x].name}</b></span><i>↗</i></button>)}</nav>
<div className="mg-grid"><section className="mg-main"><div className="mg-game-heading"><span className="mg-chip">{game==="ten"?"도토리게임":"균형 챌린지"}</span><h2>{g.hint}</h2><p>{g.desc}</p></div><GameCanvas key={game+":"+(session?.id||"idle")} game={game} session={session} stop={stop} onFinish={finished}/>
<div className="mg-actions">{phase==="playing"?<button className="mg-button secondary" onClick={()=>T(x=>x+1)}>이번 판 그만하기</button>:pending?<button className="mg-button" disabled={phase==="saving"} onClick={()=>void save(pending)}>{phase==="saving"?"기록 저장 중…":"기록 저장 다시 시도"}</button>:<button className="mg-button" disabled={phase==="starting"||authStatus==="loading"} onClick={()=>void start()}>{phase==="starting"?"게임 준비 중…":authStatus!=="authenticated"?"로그인하고 시작":result?"한 판 더 하기":"한 판 시작하기"}<span>→</span></button>}<small>{phase==="playing"?"화면을 벗어나면 이번 판이 종료돼요.":"도토리 사용 없이 자유롭게 도전하세요."}</small></div>{error&&<div role="alert" className="mg-warning">{error}</div>}{result&&<div className="mg-result"><small>{result.status==="finished"?(result.eligible?"기록 저장 완료":"랭킹 제외 기록"):result.status==="abandoned"?"이번 도전을 마쳤어요":"랭킹 미반영"}</small><strong>{result.status==="finished"?formatMetric(game,result.metric):"다음 판에 다시 도전!"}</strong><p>{result.message||"회원별 최고기록 한 개가 랭킹에 반영됩니다."}</p></div>}
<section className="mg-how"><h3>이렇게 플레이해요</h3>{game==="ten"?<ol><li><b>01</b>마우스나 손가락으로 숫자 도토리를 네모 안에 묶어요.</li><li><b>02</b>합계가 정확히 10이면 사라져요. 한 개에 1점!</li><li><b>03</b>빈칸을 가로질러 선택할 수 있어요. 제한시간은 120초.</li></ol>:<ol><li><b>01</b>← → 또는 A / D로 기우는 방향을 조절해요.</li><li><b>02</b>너무 오래 누르면 반대로 넘어져요. 짧게 나눠 눌러요.</li><li><b>03</b>시간이 지나면 바람이 강해져요. 최대 도전은 600초.</li></ol>}<p>{game==="ten"?"모바일은 가로 화면이나 전체화면으로 더 넓게 즐길 수 있어요.":"모바일은 화면 아래 왼쪽·오른쪽 버튼을 눌러요."} 화면 이탈·중도 종료한 판은 순위에 반영되지 않아요.</p></section></section>
<aside className="mg-sidebar"><section className="mg-personal"><small>MY BEST</small><h3>나의 최고기록</h3><strong>{mine?formatMetric(game,mine.metric):"첫 기록을 기다려요"}</strong><span>{mine?"전체 "+mine.rank.toLocaleString()+"위":authStatus==="authenticated"?"첫 도전을 시작해 보세요.":"로그인 후 기록을 남겨 보세요."}</span></section><section className="mg-board"><div className="mg-rank-heading"><div><small>HALL OF FAME</small><h3>최고기록 TOP 100</h3></div><button disabled={locked||rankLoading} onClick={()=>void load()} aria-label="랭킹 새로고침">↻</button></div><p className="mg-rank-note">{g.name} · {game==="ten"?"점수":"생존시간"} 순</p>{rankError?<p className="mg-empty">{rankError}</p>:rankLoading&&!ranks.length?<p className="mg-empty">랭킹 불러오는 중…</p>:!ranks.length?<p className="mg-empty">아직 기록이 없어요.<br/>첫 기록의 주인공이 되어 보세요.</p>:<ol className="mg-ranks">{ranks.map(x=><li key={x.rank}><span>{String(x.rank).padStart(2,"0")}</span><b>{x.nickname}</b><strong>{formatMetric(game,x.metric)}</strong></li>)}</ol>}<p className="mg-board-note">한 사람당 최고기록 하나만 표시해요.<br/>동점이면 먼저 기록한 사람이 앞서요.</p></section></aside></div><footer className="mg-footer"><span>WANGCHU ARCADE · 함께 만드는 작은 기록들</span><a href="/">홈으로 돌아가기 ↗</a></footer></div></main>;
}
